<?php

/**
 * DowntimeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DowntimeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DowntimeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Downtime');
    }
}