<?php

/**
 * Downtime
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    checkup
 * @subpackage model
 * @author     Nathanaël Martel <nathanael@fam-martel.eu>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Downtime extends BaseDowntime
{
}
