

# default rules
site:
  url:   /site
  param: { module: site, action: index }
  
homepage:
  url:   /
  param: { module: site, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
