
Site:
  tableName: site
  columns:
    url: string(255)
    title: string(255)
    ip: string(255)
    host : string(255)
    http_code: string(255)
    effective_url: string(255)
    last_check: date
    
  relations:
    Downtimes:
      class: Downtime
      local: id
      foreign: site_id
    
  actAs:
    Timestampable:
    Sluggable: { fields: [url], uniqueBy: [id], canUpdate: false }

  options:
    collate: utf8_unicode_ci
    charset: utf8
    
Downtime:
  tableName: downtime
  columns:
    http_code: string(255)
    time: {type: datetime, primary: true}
    site_id: {type: integer, primary: true}
    
  relations:
    Site:
      class: Site
      local: site_id
      foreign: id

  options:
    collate: utf8_unicode_ci
    charset: utf8
    
    
    